import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import connectToDatabase from '@/utils/mongodb';
import User from '@/app/models/User'; // --- 1. Import the User model ---

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // --- 2. Test connection and model loading ---
  try {
    await connectToDatabase();
    console.log('✅ MongoDB connection established');
    // The '!!' converts the User object to a boolean (true if it exists, false otherwise)
    console.log('✅ User model loaded successfully:', !!User);
  } catch (error) {
    console.error('❌ Database or Model loading failed:', error.message);
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}