import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import connectToDatabase from '@/utils/mongodb';
import User from '@/app/models/User';
import Providers from "@/components/Providers"; // <-- 1. IMPORT THE NEW COMPONENT

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  try {
    await connectToDatabase();
    console.log('✅ MongoDB connection established');
    console.log('✅ User model loaded successfully:', !!User);
  } catch (error) {
    console.error('❌ Database or Model loading failed:', error.message);
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 2. WRAP YOUR CHILDREN WITH THE PROVIDER */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}